import logging
import argparse
import os
import sys

# Add project root to sys.path to allow importing reasoning_engine
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from reasoning_engine import engine as reasoning_engine # Import the reasoning engine

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def accept_task(user_id: str, task_description: str):
    """
    Accepts a user ID and task description, generates a plan using the
    reasoning engine, and logs both.
    """
    logging.info(f"Task received for user_id '{user_id}': {task_description}")

    # Generate plan using the reasoning engine
    plan = reasoning_engine.generate_plan(user_id, task_description)

    if plan:
        logging.info(f"Generated plan for user_id '{user_id}':")
        for i, step in enumerate(plan):
            logging.info(f"  Step {i+1}: {step}")
    else:
        logging.warning(f"No plan generated by the reasoning engine for user_id '{user_id}' and task: {task_description}")
        logging.warning("This could be due to a missing/invalid OPENAI_API_KEY or an issue with the LLM.")


    # Placeholder for dispatching the task (and now the plan) to a scheduler
    # print(f"Dispatching task for user '{user_id}' with plan to scheduler (not implemented yet)...")

def main():
    parser = argparse.ArgumentParser(description="Task Orchestrator")
    parser.add_argument("user_id", type=str, help="The ID of the user initiating the task.")
    parser.add_argument("task_description", type=str, help="A description of the task to be executed.")
    args = parser.parse_args()

    # Before calling accept_task, ensure environment variables like OPENAI_API_KEY are loaded
    # if this script is the entry point. For simplicity in module structure,
    # we assume .env is loaded by the execution environment or a top-level script.
    # If OPENAI_API_KEY is needed by reasoning_engine and not set, generate_plan will handle it.

    # For testing, explicitly load .env if running this directly and it's the main entry point
    if __name__ == "__main__":
        try:
            from dotenv import load_dotenv
            dotenv_path = os.path.join(project_root, '.env')
            if os.path.exists(dotenv_path):
                load_dotenv(dotenv_path=dotenv_path)
                logging.info(f"Loaded .env file from {dotenv_path}")
            else:
                logging.info(".env file not found, relying on environment-set variables.")
        except ImportError:
            logging.info("python-dotenv not installed. Relying on environment-set variables.")
        except Exception as e:
            logging.error(f"Error loading .env: {e}")


    accept_task(args.user_id, args.task_description)

if __name__ == "__main__":
    main()
